SELECT
    B.*
FROM
    (
    SELECT
        UMLHDRS1.IVNO1 AS "INVOICE NUMBER",
        UMLHDRS1.RFDCNO AS "DOCUMENT NUMBER",
        CASE
            WHEN UMLHDRS1.IVTYP IN ('P', 'C') THEN 'PARTS COUNTER'
            WHEN UMLHDRS1.IVTYP IN ('W', 'B') THEN 'WORK ORDER - PARTS'
        END AS "INVOICE TYPE",
        UMLHDRS1.CUNO AS "CUSTOMER NUMBER",
        UMLHDRS1.EQMFSN AS "SERIAL NUMBER",
        UMLHDRS1.EQMFM1 AS "MODEL NUMBER",
        DATE(SUBSTRING(UMLHDRS1.IVDAT8, 1, 4)|| '-' || SUBSTRING(UMLHDRS1.IVDAT8, 5, 2)|| '-' || SUBSTRING(UMLHDRS1.IVDAT8, 7, 2)) AS "INVOICE DATE",
        UMLHDRS1.DIVI AS "DIVISION",
        MSLDETL1.SOS1 AS "SOS",
        MSLDETL1.WOSGNO AS "SEGMENT",
        MSLDETL1.PANO20 AS "PART NO",
        MSLDETL1.DS5 AS "DESCRIPTION",
        MSLDETL1.QTY5 AS "QTY",
        MSLDETL1.UNCS AS "DN",
        MSLDETL1.UNLS AS "DBS LIST",
        MSLDETL1.CONLST AS "TRUE LIST",
        (MSLDETL1.UNSEL + MSLDETL1.ADJAMT) AS "UNIT SELL/TRANSACTION PRICE",
        MSLDETL1.ADJAMT AS "DISCOUNT AMOUNT (DBS)",
        ((MSLDETL1.UNSEL + MSLDETL1.ADJAMT)-MSLDETL1.CONLST) AS "DISCOUNT AMOUNT (TRUE LIST)",
        MSLDETL1.ADJPCT AS "DBS DISCOUNT PERCENT",
        (1-((MSLDETL1.UNSEL + MSLDETL1.ADJAMT)/(MSLDETL1.CONLST))) AS "TRUE DISCOUNT %",
        ((MSLDETL1.UNSEL + MSLDETL1.ADJAMT)*(MSLDETL1.QTY5)) AS "TRANS (EXT)",
        (MSLDETL1.UNCS * MSLDETL1.QTY5) AS "DN (EXT)",
        CASE
            WHEN MSLDETL1.PANO20  IN 'PCCFREEGIFT' THEN 'PCCFREEGIFT'
            WHEN MSLDETL1.PANO20 NOT IN 'PCCFREEGIFT' THEN MSLDETL1.MPPGMN
        END AS "PROGRAM",
        CIPNAME0.CUNM AS "CUSTOMER NAME"
    FROM
        (LIBE30H.UMLHDRS1 UMLHDRS1
    INNER JOIN LIBE30H.MSLDETL1 MSLDETL1 ON
        UMLHDRS1.IVNO1 = MSLDETL1.IVNO1)
    INNER JOIN LIBE30H.MSPSEGS0 MSPSEGS0 ON
        UMLHDRS1.IVNO1 = MSPSEGS0.IVNO1
        AND MSLDETL1.WOSGNO = MSPSEGS0.WOSGNO
    INNER JOIN LIBE30.CIPNAME0 CIPNAME0 ON
        CIPNAME0.CUNO = UMLHDRS1.CUNO
    INNER JOIN (SELECT MPPGMN
			FROM LIBE30.PCLPMHD0
			WHERE THRDTE  > 20250000
			AND PRMIND = 'Y') AS "PROMO" ON
			MSLDETL1.MPPGMN = PROMO.MPPGMN
    WHERE
        1 = 1
        AND UMLHDRS1.HSTI = ''
        AND MSPSEGS0.TLSELL <> 0
        AND MSPSEGS0.WOOPNO = ''
        AND MSLDETL1.RCDTP = 'A'
        AND LEFT(UMLHDRS1.IVDAT8,4) IN ('2025','2024','2023')
      AND UMLHDRS1.CUNO NOT LIKE 'I%'
  ) AS "B"
WHERE
    2 = 2
    LIMIT 30
